/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:327776ec-d1e4-4ad4-99c3-8890815b3090",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PIY96OxtS",
    "aws_user_pools_web_client_id": "3ndqpf0997g69sga9377uuhn71",
    "oauth": {
        "domain": "tailwindauth4cf825c5-4cf825c5-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/profile/",
        "redirectSignOut": "http://localhost:3000/profile/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
